"""add_is_prepared_to_order_items

Revision ID: 3c7fbfca20c4
Revises: 4b4cb7dac7a3
Create Date: 2026-05-11 11:49:26.187001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c7fbfca20c4'
down_revision: Union[str, Sequence[str], None] = '4b4cb7dac7a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bills_bill_number_key'), 'bills', type_='unique')
    op.drop_index(op.f('uq_discount_configs_name_active'), table_name='discount_configs', postgresql_where='(is_active = true)')
    op.create_unique_constraint(None, 'discount_configs', ['name'])
    op.add_column('order_items', sa.Column('is_prepared', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_index(op.f('uq_tax_configs_name_active'), table_name='tax_configs', postgresql_where='(is_active = true)')
    op.create_unique_constraint(None, 'tax_configs', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tax_configs', type_='unique')
    op.create_index(op.f('uq_tax_configs_name_active'), 'tax_configs', ['name'], unique=True, postgresql_where='(is_active = true)')
    op.drop_column('order_items', 'is_prepared')
    op.drop_constraint(None, 'discount_configs', type_='unique')
    op.create_index(op.f('uq_discount_configs_name_active'), 'discount_configs', ['name'], unique=True, postgresql_where='(is_active = true)')
    op.create_unique_constraint(op.f('bills_bill_number_key'), 'bills', ['bill_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
